//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtel.PromoFormula {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class tr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal tr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xtel.PromoFormula.tr", typeof(tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not of &apos;{1}&apos; type.
        /// </summary>
        internal static string _0__is_not__1__type {
            get {
                return ResourceManager.GetString("_0__is_not__1__type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not a digit.
        /// </summary>
        internal static string _0__not_a_digit {
            get {
                return ResourceManager.GetString("_0__not_a_digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not an arithmetic symbol.
        /// </summary>
        internal static string _0__not_an_arithmetic_symbol {
            get {
                return ResourceManager.GetString("_0__not_an_arithmetic_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A and B must be of a same type.
        /// </summary>
        internal static string a_and_b_must_be_of_a_same_type {
            get {
                return ResourceManager.GetString("a_and_b_must_be_of_a_same_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot transform &apos;{0}&apos; into a string.
        /// </summary>
        internal static string cannot_transform__0__into_a_string {
            get {
                return ResourceManager.GetString("cannot_transform__0__into_a_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t apply &apos;{0}&apos; on {1}.
        /// </summary>
        internal static string cant_apply__0__on__1 {
            get {
                return ResourceManager.GetString("cant_apply__0__on__1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t compare objects of &apos;{0}&apos; type.
        /// </summary>
        internal static string cant_compare_objects_of__0__type {
            get {
                return ResourceManager.GetString("cant_compare_objects_of__0__type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid numeric literal.
        /// </summary>
        internal static string invalid_numeric_literal {
            get {
                return ResourceManager.GetString("invalid_numeric_literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; cannot be applied to operands of type &apos;{1}&apos;.
        /// </summary>
        internal static string operator__0__cannot_be_applied_to_operands_of_type__1 {
            get {
                return ResourceManager.GetString("operator__0__cannot_be_applied_to_operands_of_type__1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator &apos;{0}&apos; cannot be applied to operands of type &apos;{1}&apos; and &apos;{2}&apos;.
        /// </summary>
        internal static string operator__0__cannot_be_applied_to_operands_of_type__1__and__2 {
            get {
                return ResourceManager.GetString("operator__0__cannot_be_applied_to_operands_of_type__1__and__2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected char at: {0}.
        /// </summary>
        internal static string unexpected_char_at__0 {
            get {
                return ResourceManager.GetString("unexpected_char_at__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token: {0}.
        /// </summary>
        internal static string unexpected_token__0 {
            get {
                return ResourceManager.GetString("unexpected_token__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown constant token: {0}.
        /// </summary>
        internal static string unknown_constant_token__0 {
            get {
                return ResourceManager.GetString("unknown_constant_token__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown operation: {0}.
        /// </summary>
        internal static string unknown_operation__0 {
            get {
                return ResourceManager.GetString("unknown_operation__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown operator: {0}.
        /// </summary>
        internal static string unknown_operator__0 {
            get {
                return ResourceManager.GetString("unknown_operator__0", resourceCulture);
            }
        }
    }
}
